### ISSUE TITLE
Not working with recent Chrome updates 

### ISSUE THREAD

**Issue by findela** [EvandroLG/ts-audio#16]
I tried to work on your code and audio is not playing on load which is my requirement. 

PFA for more info and also any help appreciated.
![Screenshot from 2020-08-30 23-23-29](https://user-images.githubusercontent.com/8926058/91666084-c6c81d00-eb17-11ea-81ba-a4380f0fd30e.png)

**Comment by EvandroLG** [comment]
Hi @findela 

I don't think we can avoid it, because it's part of the browser implementation by default not allow playing sounds and videos without user interaction.

If you go to `chrome://flags/`, there's an option that you can enable to solve your issue (`Autoplay policy `), but I'm sure it's not a solution for your problem :)

My recommendation is to design a play button for the user to interact. Is this possible for your application? :)
